### ISSUE TITLE
Add all recent projects to the project dashboard

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/dashboard#5]
https://github.com/open-innovations/dashboard/blob/main/data/projects.csv

**Comment by luke-strange** [comment]
I've added JRF and leeds schools cultural engagement to the `projects.csv` file in dashboard. Not sure what else needs adding.

@slowe @taz-chiles

**Comment by slowe** [comment]
@luke-strange A JRF North Insight Finder hub page (on our website) is being worked on by @ChristianSpence. Not yet ready to update the link for that.

**Comment by ODILMichelle** [comment]
@luke-strange/ @taz-chiles/ @slowe could 1 of you come up with a list of the projects you think we need to add & then ask the rest of us to review this, and ticket any other materials that are needed.

Keen to retain the 1 or 2 people per card approach, so we know who is responsible for moving on what.

**Comment by luke-strange** [comment]
- [x] lcc economics

**Comment by slowe** [comment]
Here is the list that I am aware of. These need to be checked that they are up-to-date in the dashboard file @luke-strange links at the top. But they may also need individual "hub" pages creating/updating. Some may be best on a "World of economics" page on the website rather than have specific hub pages.
- [ ] LSIP (perhaps add to "World of Economics" page rather than create another page on our website)
- [x] YFF Phase 2 (add to https://open-innovations.org/projects/youth-futures-foundation/)
- [x] University of Leeds project
- [ ] Tax devolution
- [ ] JRF North Insight Finder (hub page in progress)

**Comment by luke-strange** [comment]
Currently those things are all in the projects dashboard (apart from UoL project - not sure what that is?). The links are as follows:

- LSIP link is to the LSIP website. (do we want it to link to a World of economics page instead?)
- YFF project link goes to the right place. We just need to add phase 2 info onto that page.
- Tax devo goes to Christian's github repo for that project. Should it go somewhere else?
- JRF currently links to the github repo for jrf. This can be updated once it has a project hub page.

**Comment by ODILMichelle** [comment]
@slowe there is also probably the Leeds City Council Economic Data Partner, unless that is already taken care of?

Cool, University of Leeds project is also the Leeds-Schools-Cultural-Engagement project. There is a website & repo for this, both on the OI github.

In terms of tickets it looks like there are a few things:
- Re: YFF - there is already a ticket for updating the hub page for Phase 2. @taz-chiles has taken this on (https://github.com/open-innovations/yff-data/issues/105). YFF Phase 2 shouldn't be a separate project I think, I think it's probably all just YFF - but I'll leave others to make that call. 
- There is probably a ticket to be made re: creating a hub page for the 'Leeds Schools Cultural Engagement' project, which will be a joint effort probably between myself and @slowe (Stuart to create the hub page & add website and repo links, and me to help write a blog post). Raised this as ticket open-innovations/leeds-schools-cultural-engagement#15 
- Ensure there is a ticket for making a project page for JRF

Outside of that, there is something to work out with others about whether LSIP and Tax devo should do on to the world of economics, or have its own hub page which is linked to from the world of economics. (latter of which kind of feels appropriate given there might be various blogs about this)

**Comment by ODILMichelle** [comment]
I've done the stuff I'm involved with on this. I'll leave @ChristianSpence to work with you all on the more economics focussed projects!

**Comment by gilesdring** [comment]
Same comment about where this resides as open-innovations/platform#8 - to discuss with @slowe next week

**Comment by slowe** [comment]
Yes, this could be attached to the dashboard repo instead.

**Comment by luke-strange** [comment]
Is this done?

**Comment by gilesdring** [comment]
Check with @ChristianSpence

**Comment by ChristianSpence** [comment]
> * Tax devo goes to Christian's github repo for that project. Should it go somewhere else?

I transferred the tax-devolution repo from my personal account to OI last week, so that's ready for updating

**Comment by gilesdring** [comment]
Dome this. Closing ticket, as assume this is all...
